from  dash import html
import dash_tagcloud
from app import create_app, serve_app

app = create_app()

security_data = [
    ["Leveraged/Inverse", 36],
    ["Trading", 36],
    ["Equity", 43],
    ["Large Cap", 39],
    ["US", 35],
    ["Blend", 37],
    ["Other", 36],
    ["Global", 38],
    ["Emerging Markets", 33],
    ["Bond", 39],
    ["USD", 34],
    ["Government", 32],
    ["Europe", 33],
    ["Sector Equity", 36],
    ["Technology", 30],
    ["Commodities", 35],
    ["Japan", 29],
    ["Corporate", 32],
    ["Precious Metals", 29],
    ["Broad Basket", 28],
    ["Eurozone", 29],
    ["Consumer", 26],
    ["Goods", 26],
    ["Services", 29],
    ["Value", 29],
    ["Income", 29],
    ["UK", 28],
    ["ex Japan", 29],
    ["Asia", 28],
    ["EUR", 32],
    ["Energy", 29],
    ["Financial", 26],
    ["China", 27],
    ["Industrial", 27],
    ["Materials", 25],
    ["Healthcare", 25],
    ["High Yield", 28],
    ["Small Cap", 27],
    ["Pacific", 26],
    ["A Shares", 23],
    ["GBP", 28],
    ["Flex Cap", 26],
    ["India", 23],
    ["Korea", 23],
    ["Inflation Linked", 26],
    ["Brazil", 22],
    ["Broad", 23],
    ["Metals", 22],
    ["Local Currency", 23],
    ["Property", 26],
    ["Indirect", 26],
    ["Russia", 22],
    ["Communications", 22],
    ["Utilities", 22],
    ["Growth", 24],
    ["ex UK", 22],
    ["Latin", 22],
    ["America", 23],
    ["Ecology", 22],
    ["Canada", 21],
    ["Money", 21],
    ["Market", 21],
    ["Biotechnology", 21],
    ["Taiwan", 21],
    ["Fixed", 21],
    ["Grains", 20],
    ["Short Term", 27],
    ["Ultra", 20],
    ["Hedged", 26],
    ["Natural", 20],
    ["Resources", 20],
    ["Mid Cap", 27],
    ["Australia", 20],
    ["New", 20],
    ["Zealand", 20],
    ["Small/", 22],
    ["Water", 20],
    ["Turkey", 20],
    ["Softs", 19],
    ["Germany", 20],
    ["RMB", 19],
    ["Onshore", 19],
    ["Infrastructure", 19],
    ["South", 19],
    ["Africa", 20],
    ["Namibia", 19],
    ["Diversified", 24],
    ["Alt", 23],
    ["Systematic", 18],
    ["Futures", 18],
    ["ex Russia", 18],
    ["Emerging", 20],
    ["Indonesia", 18],
    ["Islamic", 20],
    ["Alternative", 18],
    ["Relative", 17],
    ["Arbitrage", 17],
    ["Agriculture", 19],
    ["Livestock", 17],
    ["Long", 17],
    ["Term", 17],
    ["Italy", 17],
    ["Not Categorised", 17],
    ["North", 17],
    ["Private", 17],
    ["Currency", 15],
    ["BRIC", 15],
    ["Convertible", 15],
    ["France", 15],
    ["Biased", 15],
    ["Frontier", 15],
    ["Markets", 15],
    ["Israel", 15],
    ["Large/", 15],
    ["Nordic", 15],
    ["Poland", 15],
    ["Switzerland", 15],
    ["Thailand", 15],
    ["Moderate", 17],
    ["Allocation", 19],
    ["Vietnam", 15],
    ["Middle East", 12],
    ["Flexible", 12],
    ["Subordinated", 12],
    ["Moderately", 15],
    ["Adventurous", 12],
    ["Cautious", 12],
    ["Netherlands", 12],
    ["Spain", 12],
    ["Sweden", 12],
]

app.layout = html.Div([
    html.Div([
        html.Div([
            html.H1('Dash Tag Cloud'),
            dash_tagcloud.DashTagcloud(list=security_data, width=1200, height=600)
            ], className='app-inner')
    ], className='app-outer')
])

if __name__ == '__main__':
    serve_app(app)
